version: '3'
services:
  tarot:
    build: .
    image: chaosexanima/tarot-aide
    volumes:
      - ./prisma/dev.db:/db/tarot.db
      - ./uploads:/uploads

  proxy:
    image: nginx:alpine
    ports:
      - 3000:3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tarot
