version: '3'
services:
  tarot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: chaosexanima/tarot-aide
    environment:
      - BASE_PATH=/tarot
      - DATABASE_URL=file:/db/tarot.db
      - UPLOAD_PATH=/uploads
    volumes:
      - ../dev.db:/db/tarot.db
      - ../uploads:/uploads

  proxy:
    image: nginx:alpine
    ports:
      - 3000:3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tarot
