services:
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_AUTO_UPGRADE: 'true'
      MARIADB_DATABASE: tarot

volumes:
  db_data:
