include:
  - path:
      - docker-compose.dev.yml

services:
  tarot:
    env_file: .env.local
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: chaosexanima/tarot-aide
    ports:
      - 3001:3000
    environment:
      UPLOAD_PATH: /uploads
    volumes:
      - ../uploads:/uploads
    depends_on:
      - mysql
