import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from 'styles/Home.module.css';
import { HTMLProps, PropsWithChildren, ReactHTMLElement } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Tarot Aide</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div className={styles.description}>
					<p>Stuff to do:</p>
					<ul>
						<ListItem>Figure out base functionality</ListItem>
						<ListItem>Pick a damn front end library</ListItem>
						<ListItem>Lay out pages w/ mock data</ListItem>
						<ListItem>Figure out storage</ListItem>
						<ListItem>Upload stuff</ListItem>
						<ListItem>Wire 'er up</ListItem>
						<ListItem>Docker deployment</ListItem>
					</ul>
				</div>
			</main>
		</>
	);
}

function ListItem({
	children,
	...inputProps
}: PropsWithChildren<HTMLProps<HTMLInputElement>>) {
	const id = (children?.toString() ?? 'no-id')
		.toLowerCase()
		.replaceAll(/[^a-z0-9]+/g, '-');
	return (
		<li>
			<input
				type="checkbox"
				name={id}
				id={id}
				value="1"
				{...inputProps}
			/>
			&nbsp;
			<label htmlFor={id}>{children}</label>
		</li>
	);
}
